angular.module('app.loggedIn.measurement.include',[
	'app.loggedIn.measurement.directives.list',
	'app.loggedIn.measurement.controllers.list',
	'app.loggedIn.measurement.models',
	'app.loggedIn.measurement.controllers.add',
	'app.loggedIn.measurement.directives.add',
	'app.loggedIn.measurement.controllers.edit',
	'app.loggedIn.measurement.directives.edit'
])